### ISSUE TITLE
No possibility to download artifact from provider version 2.3.1

### ISSUE THREAD

**Issue by sgabenov** [jfrog/terraform-provider-artifactory#118]
After moving from provider verson 2.2.15 to 2.3.1 terraform could not download or update artifact from repository. If output path exist, it says that artifact is different from upstream source and drop with error (even with force_overwrite = true). When the output path does not have any file, it fails with error - no file or path available

**Requirements for and issue**
```tcl
data "artifactory_file" "ac_api_changelog_indexer_code" {
  repository      = "nibr-generic"
  path            = "/intuence_discovery/ac_api_changelog_indexer/develop_ac_api_changelog_indexer_latest.zip"
  output_path     = "${path.module}/resources/code_ac_api_changelog_indexer.zip"
  force_overwrite = true
}
```

terraform plan / terraform apply

```
╷
│ Error: stat ./resources/code_ac_api_changelog_indexer.zip: no such file or directory
│ 
│   with data.artifactory_file.ac_api_changelog_indexer_code,
│   on main.tf line 111, in data "artifactory_file" "ac_api_changelog_indexer_code":
│  111:   output_path     = "${path.module}/resources/code_ac_api_changelog_indexer.zip"
│ 
╵
```

**Expected behavior**
Download artifact

**Additional context**
The problem begin to exist after move to 2.3.1 version. Previously the same code worked fine for a long period

**Comment by chb0github** [comment]
2.3.1 is a major version release - perfect backward compatibility was not expected. I will investigate

**Comment by chb0github** [comment]
v2.3.1 is much more stringent about how it validates now and in this case, only checks for its existance. Obviously, the file may not be there; thisis a bug.  This should be change to make sure you _can_ write that file.

**Comment by chb0github** [comment]
This problem should now be resolved

**Comment by velith** [comment]
Hi. I recently started using this provider and the issue was still present on v2.3.4

**Comment by chb0github** [comment]
Sigh .. ok. I will have a look again today. Thank you

**Comment by chb0github** [comment]
Ok. Rather than hold up this change because of testing issues, I have tested this TF script:

```tcl
data "artifactory_file" "ac_api_changelog_indexer_code" {
  repository      = "integration-helm"
  path            = "artifactory-11.7.2.tgz"
  output_path     = "${path.cwd}/resources/integration-helm/artifactory-11.7.2.tgz"
  force_overwrite = true
}
```
and it works. I will keep this ticket open until tests are sorted out, but I will make a release right now

**Comment by velith** [comment]
Awesome! Can confirm it works on v2.3.7 :tada: :pray:

**Comment by chb0github** [comment]
It's fixed in the latest version. If you have any issues let me now
