### ISSUE TITLE
artifactory_remote_vcs_repository always wants to apply non-existing changes

### ISSUE THREAD

**Issue by blabu23** [jfrog/terraform-provider-artifactory#1232]
**Describe the bug**

My artifactory_remote_vcs_repository always tries to apply a change but changes nothing:

`
Terraform will perform the following actions:

  # artifactory_remote_vcs_repository.vcs["ansiblegalaxy"] will be updated in-place
  ~ resource "artifactory_remote_vcs_repository" "vcs" {
        # (44 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions in workspace "sams"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

artifactory_remote_vcs_repository.vcs["ansiblegalaxy"]: Modifying...
artifactory_remote_vcs_repository.vcs["ansiblegalaxy"]: Modifications complete after 0s
`
My first analysis showed one IMHO wrong topic. The API call to fetch the repository from Artifactory results in

`
{'allowAnyHostAuth': False,
 'archiveBrowsingEnabled': True,
 'assumedOfflinePeriodSecs': 300,
 'blackedOut': False,
 'blockMismatchingMimeTypes': True,
 'bypassHeadRequests': False,
 'clientTlsCertificate': '',
 'contentSynchronisation': {'enabled': False,
                            'properties': {'enabled': False},
                            'source': {'originAbsenceDetection': False},
                            'statistics': {'enabled': False}},
 'curated': False,
 'description': ' (local file cache)',
 'disableProxy': False,
 'disableUrlNormalization': False,
 'downloadRedirect': False,
 'enableCookieManagement': False,
 'environments': [],
 'excludesPattern': '',
 'hardFail': False,
 'includesPattern': 'freeipa/ansible-freeipa/**,ansible-collections/ansible.posix/**,containers/ansible-podman-collections/**,redhat-cop/**',
 'key': 'ansiblegalaxy',
 'listRemoteFolderItems': False,
 'localAddress': '',
 'maxUniqueSnapshots': 0,
 'metadataRetrievalTimeoutSecs': 60,
 'mismatchingMimeTypesOverrideList': '',
 'missedRetrievalCachePeriodSecs': 1800,
 'notes': '',
 'offline': False,
 'packageType': 'vcs',
 'passThrough': False,
 'password': '',
 'priorityResolution': False,
 'propagateQueryParams': False,
 'propertySets': ['artifactory'],
 'proxy': '',
 'rclass': 'remote',
 'repoLayoutRef': 'vcs-default',
 'retrievalCachePeriodSecs': 7200,
 'retrieveSha256FromServer': False,
 'sendContext': False,
 'shareConfiguration': False,
 'signedUrlTtl': 90,
 'socketTimeoutMillis': 15000,
 'storeArtifactsLocally': True,
 'synchronizeProperties': False,
 'unusedArtifactsCleanupPeriodHours': 0,
 'url': 'https://github.com/',
 'username': '',
 'vcsGitDownloadUrl': '',
 'vcsGitProvider': 'GITHUB',
 'vcsType': 'GIT',
 'xrayDataTtl': 90,
 'xrayIndex': False}
`

Only difference to a second repo configured via terraform is the field **vcsGitDownloadUrl** which is missing in the working repo!

Artifactory version: 7.104.13 (EnterpriseX, Self-Hosted)
Terraform version: v1.10.2
Provider version: 12.9.1

**Expected behavior**

After applying the change it should not offer to change it again. Additionally it should tell me the change it itends to apply (only hidden changes displayed)

**Comment by blabu23** [comment]
Any way I can support in this issue?

**Comment by jcoste** [comment]
I have the same problem with other resources : 
```
  # artifactory_remote_bower_repository.bower-proxy-official will be updated in-place
  ~ resource "artifactory_remote_bower_repository" "bower-proxy-official" {
        # (34 unchanged attributes hidden)
    }

  # artifactory_remote_cocoapods_repository.cocoapods-proxy-official will be updated in-place
  ~ resource "artifactory_remote_cocoapods_repository" "cocoapods-proxy-official" {
        # (34 unchanged attributes hidden)
    }

  # artifactory_remote_composer_repository.php-proxy-official will be updated in-place
  ~ resource "artifactory_remote_composer_repository" "php-proxy-official" {
        # (34 unchanged attributes hidden)
    }

  # artifactory_remote_vcs_repository.vcs-proxy-github will be updated in-place
  ~ resource "artifactory_remote_vcs_repository" "vcs-proxy-github" {
        # (34 unchanged attributes hidden)
    }
```

Provider version 12.9.2
Artifactory 7.98.13

**Comment by madelaney** [comment]
I'm hitting a similar issue:

```console
OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

OpenTofu will perform the following actions:

  # artifactory_remote_cocoapods_repository.cocoapods-remote will be updated in-place
  ~ resource "artifactory_remote_cocoapods_repository" "cocoapods-remote" {
        # (31 unchanged attributes hidden)
    }
```

Using OpenTofu
```console
OpenTofu v1.9.0
on darwin_arm64
+ provider registry.opentofu.org/hashicorp/null v3.2.3
+ provider registry.opentofu.org/hashicorp/random v3.7.2
+ provider registry.opentofu.org/jfrog/artifactory v12.9.2
+ provider registry.opentofu.org/jfrog/platform v2.2.3
```

**Comment by srinivasgowda097** [comment]
@madelaney @blabu23 @jcoste Thanks for the report! I've added this to our plan to investigate and fix it soon in next release

**Comment by srinivasgowda097** [comment]
@madelaney @blabu23 @jcoste Fix available in `12.9.6` version

**Comment by blabu23** [comment]
I created a new ticket, since this problem is not solved yet: #1334
