### ISSUE TITLE
Incompatible provider version jfrog/artifactory

### ISSUE THREAD

**Issue by vasanthig21** [jfrog/terraform-provider-artifactory#240]
It is not possible to automatically install the provider via terraform init on linux_amd64

<img width="769" alt="Screen Shot 2021-12-10 at 7 16 01 PM" src="https://user-images.githubusercontent.com/94625595/145656901-5550cc73-4b7c-4f0a-b87c-b0a397b6e7f3.png">

As a workaround, I tried with all versions of jfrog/artifactory. But all of them are giving same error and also tried with commenting the version in jfrog/artifactory provider block. Still the same error.

Can anyone help me with this issue?

below is the versions.tf file where versions of required providers were declared.

terraform {
required_version = "~> 1.0"
backend "remote" {
hostname = "app.terraform.io"
organization = "platformzero"
workspaces {
name = "tf-artifactory-cloud"
}
}

required_providers {
artifactory = {
source = "jfrog/artifactory"
#version = "2.6.21"
}
}
}

provider "azurerm" {
#version = "= 2.89.0"
subscription_id = var.subscription_id
tenant_id = var.tenant_id
features {}
}

**Comment by stefanfreitag** [comment]
Hi,

I had no issue using the latest provider version 2.6.22 on my local machine (Kubuntu 21.10)

```
❯ terraform init --upgrade

Initializing the backend...

Initializing provider plugins...
- Finding jfrog/artifactory versions matching "2.6.22"...
- Using previously-installed jfrog/artifactory v2.6.22
❯ terraform init --upgrade

Initializing the backend...

Initializing provider plugins...
- Finding jfrog/artifactory versions matching "2.6.22"...
- Using previously-installed jfrog/artifactory v2.6.22

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

running the code in a pipeline (base os: ubuntu 20.04, hosted agent on Azure)  I ran into the same error

```
+ terraform init --upgrade

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding jfrog/artifactory versions matching "2.6.22"...
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/jfrog/artifactory v2.6.22 does not have a
│ package available for your current platform, linux_amd64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all
│ providers are available for all platforms. Other versions of this provider
│ may have different platforms supported.

```

**Comment by mikeycmccarthy** [comment]
I'm having the same issues here on an Intel mac. I'm trying an upgrade from v2.2.12 to anything else and getting

```bash
Error: Incompatible provider version
│
│ Provider registry.terraform.io/jfrog/artifactory v2.2.11 does not have a package available for your current platform, darwin_amd64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.
```
@stefanfreitag I suspect what you're seeing when it works is a previously downloaded instance of the provider, note the line:


```bash
- Using previously-installed jfrog/artifactory v2.6.22
```

That's what I see too when I revert back to my original version.

**Comment by cappyzawa** [comment]
It seems that the key registered in the registry does not exist.

```bash
$ curl -s https://registry.terraform.io/v1/providers/jfrog/artifactory/2.6.22/download/darwin/amd64 | jq .
{
  "errors": [
    "signing key 6B219DCCD7639232 not found for jfrog"
  ]
}
```

**Comment by maxdanilov** [comment]
We're experiencing the same issue, with all versions of the provider.

**Comment by aliculPix4D** [comment]
Same issue here with version `2.6.21`, but not with `2.6.22`. I am using Ubuntu 20.04.

**Comment by cappyzawa** [comment]
@aliculPix4D Isn't it because you have `2.6.22` in your machine?
(Could you check `ls .terraform/providers/registry.terraform.io/jfrog/artifactory/`, please?)

I am getting the following error regardless of os or version.
```
$ curl https://registry.terraform.io/v1/providers/jfrog/artifactory/2.6.22/download/linux/amd64
{"errors":["signing key 6B219DCCD7639232 not found for jfrog"]}
```

I think this is probably happening in all versions.

**Comment by aliculPix4D** [comment]
@cappyzawa I just did a fresh `terraform init`; No issues with `2.6.22` for me. 
```
ls .terraform/providers/registry.terraform.io/jfrog/artifactory/2.6.22/linux_amd64 
LICENSE  README.md  terraform-provider-artifactory_v2.6.22
```
doing the same with `2.6.21` results in:
```
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/jfrog/artifactory v2.6.21 does not have a package available for your current platform, linux_amd64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this
│ provider may have different platforms supported.
```

**Comment by cappyzawa** [comment]
hmmm.

Thanks for your checking!

There seems to be no workaround on the user side, so we have to wait for the maintainer to respond.

**Comment by chb0github** [comment]
It's all automated - so, if there was an error, that would be a head scratcher. I'll talk to @alexhung

**Comment by alexhung** [comment]
We are investigating this issue. It looks like TF replaces our existing signing key with a new one (that we requested to *add*), and thus all versions signed by the existing key are no longer valid on the registry. We're working with TF to attempt to recover the existing key.

Hold on tight.

**Comment by mkellyclare** [comment]
Is there any workaround for this? Every version on registry.terraform.io/jfrog/artifactory appears to be broken for me.

**Comment by alexhung** [comment]
**Quick update:** TF is in the process of restoring the public key to the registry. They also told us that once that's restored, all the existing binaries on the registry would be available to download once again.

Stay tuned. I'll update once I heard more.

**Comment by alexhung** [comment]
**Good news** (mostly)

The public key is restored and I've published new version (2.6.23) to the registry and confirmed that it is available for install.

However, I was not able to install versions prior to 2.6.22 and I'm working with TF to determine the problem and any resolutions.

**Comment by ygeszvain** [comment]
I could successfully pull version 2.6.23. However, I am getting 403 forbidden error when connecting to our artifactory. Could you advise what could have caused the reason? The credentials have not changed.

**Comment by yoeluk** [comment]
As far as we can tell the only available version is 2.6.23, all other versions are still not available. This is not such a good news since we broke backward compatibility at 2.2.15 and not all of us can readily upgrade. Very much stuck. Sigh.

**Comment by alexhung** [comment]
@yoeluk Have you clear the cache directory and lock file? We tested all the way back to 2.6.15 and they are all available.

**Comment by yoeluk** [comment]
@alexhung yeah, we don't cache... this provider is used with several automatic pipelines and we don't commit the lock files to it either but it is possible that there is a CDN cache for my region I guess?

**Comment by yoeluk** [comment]
```
$ curl https://registry.terraform.io/v1/providers/jfrog/artifactory/2.6.23/download/linux/amd64 | jq                                                                                                          270ms  Tue 14 Dec 17:21:08 2021
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3297  100  3297    0     0  27940      0 --:--:-- --:--:-- --:--:-- 28179
{
  "protocols": [
    "5.0"
  ],
  "os": "linux",
  "arch": "amd64",
  "filename": "terraform-provider-artifactory_2.6.23_linux_amd64.zip",
  "download_url": "https://github.com/jfrog/terraform-provider-artifactory/releases/download/v2.6.23/terraform-provider-artifactory_2.6.23_linux_amd64.zip",
  "shasums_url": "https://github.com/jfrog/terraform-provider-artifactory/releases/download/v2.6.23/terraform-provider-artifactory_2.6.23_SHA256SUMS",
  "shasums_signature_url": "https://github.com/jfrog/terraform-provider-artifactory/releases/download/v2.6.23/terraform-provider-artifactory_2.6.23_SHA256SUMS.sig",
  "shasum": "ea27461d7f70018a4cdacca1e860866d87cc416519724f52aac068f83e14788e",
  "signing_keys": {
    "gpg_public_keys": [
      {
        "key_id": "6B219DCCD7639232",
        "ascii_armor": "-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nmQGiBFICOY4RBADcL9qr50XhClS0yjpKipFKVaUutu7gFXeJdrNbMD3Dn9u0MH2R\nSDg2X8V7fH6UgpRxCKAijEjWohd3TfDv8Hlbdr2w9590GTsF71VqnXXXQIQRVedS\ntSWiPs+nmCrh5sokWQISgYU/iseDb+jqhwxEEflNXxcYKfCW5UL7GKypiwCgt0az\nIa3sIPlQf7cFHyFQ3C5tOAcEAJWzlTWll2SniJwCDzqTJr/UByNe8rmMUL8aanPb\nF6msrD+UUx6hhKZVrZseK4cL8CkW1JsDgtYL+2XyJkXokRjH6NWi69XksGbyl8Yw\nHOyY5WVIUelC4MWIjd3L7wEh4woS08TvxQO3uCL3o1zNmy++Oiax5+lUUBEBRvM9\nJoTfA/9aj7CpKsbcQfM9zfOytmKyr8/O1iQFXtEY8wN5RXfdCgPKtGL5fOWkjJOY\nEri/veTYDlNxzAuuyiz4dQmRsycdbbFQ+2Yg4GLsXYDVph/v9aQSVM2GATizY3fW\nZgfd0LcIrDZVEeemUrskusyoJB8QRNjadAJUlUSdudCK6Crd4bQbSkZyb2cgSW5j\nLiA8aW5mb0BqZnJvZy5jb20+iF8EExECAB8FAlICOY4CGwMGCwkIBwMCBBUCCAMD\nFgIBAh4BAheAAAoJEGshnczXY5IyL4AAnAlSgPskfgt5YkCRkhmkZ2DuH9yBAJ9C\nKahDyOvvGzFgYC7DdG/sdseVR7kCDQRSAjmOEAgA5JlfjGrnRmfIPIJ6zyt9BicZ\nQ6RRGIgQzwy/GdDHec2Oi9VQNJFXWZaqpol8DgwCADUftA+frfbrBDsgwL+oR0sx\nTK25g4zxd5z6CLrNjqfls6IY4HLFyZgJEM10/QhUiHFDnYfPPU5p16rqDcna1ILU\niF1Xwfghq+DyVDU5dSiMXkU++6U1VjK/LhVln40K4t9cQzvnVXVyufBI08NRFSY1\nI52ZWgMvhjyUL6f+N3lVpq1zJdr08EbTdp9y+gETfKx9kzvYKPnBsp1Kg2jEeG4l\numAu78BxokwVlxmDq6XB1rip4fmHfiSPROJ2XQdQYfN/g6N3qbwcbzW2Mlmw+wAD\nBQgA1+BbITyGkRqy12/4+j7uJh2gzcFO9/Qbo+FYMoHP4ecjHFS92Y0LddHKJHs8\nJebF0C8uIApO+X9ICoCUHLhbVlOV6nhgzPgKeuouC50dnXXt+/nInpW0C3w1Mzim\nqk6he/d1gw7J/u4aPro6QIOWnZQyHhMcUJRMa+K183oUUfs8SSV6kBGGrj+qzyzN\nwdz9HcW4CyTNafl0x0sT4EqaEyv1CYj+r84h8180akKF5QxdbnCOvTncm/zqTK4a\nkPiu+WBJ9rmWmJv2xWay+kt/FMAbnOU/0AIEdktiqpiO+NkVW+s2oOd+wMMu+5Ad\nxS8KgZ5hhx7DSuq5vC4zGbPSI4hIBBgRAgAJBQJSAjmOAhsMAAoJEGshnczXY5Iy\noU8AmPhzAkXBEO2Wet/qQMyHxqYYVZEAoKMW+THuhi0PhfdsOhWReceSOKpF\n=5Jv7\n-----END PGP PUBLIC KEY BLOCK-----",
        "trust_signature": "-----BEGIN PGP SIGNATURE-----\n\niQIzBAABCAAdFiEEUYkGV8Ws20uCMIZWfXLUJo5GYPwFAl9pIxwACgkQfXLUJo5G\nYPywsw/8C8bMZq3pDKfcfoUxVIJOj2uIwAMhze+Q1jqtAF9569oStLhZ0P3Qzgv9\neGQvFFa89kEJfjl6jAkps2fz0rJMF11e24NyPrR3iEdd/I/Rc3UMHD8NrlWzlQoX\nnkcLR2yA2RfpQGOecGSOzhnn3kuaOwUo7sLHXZwsLRXACT8VdoB4qd/KXvA0PwKv\nuPe0Q8M3Ho/EOoKO+2kznR+pSF0CczYNfM+cArHn4MgDOrierV5t3XZxDEpSg01A\ngWn3NLRQsgxlJuCvUfXjYQF6zpAeT00QHOLHyiZqpr9DDomvQW2IPBLq2SxQBss7\n6cfu/pNicxlM2n5yXFVxpoQZzVaB3PMRW+xh9IEWanRYSCVuWeWniWvoZ5P1Uhsv\ndXZWyf3egYXsjyHUt5tqkPcA5KDcy6j1Z9Oaj5lKckn7jkmD8t9LE2ohHPeLr1f6\n6dYziiFNJ7kjBqMFO5WV6XR4mWaeuEvwEh0sGEVmXPhHT9ZOEsICu7Srg6a15tCV\n5lmjW1Lnvdxg2HW6kFZCSHVKkbRqDqdQ1s4rg+DgVPAvFVYXY9WWEs0ZCttcDpY9\nD0wS6BPSRB/VbrxGq9s9lGxdKeGtOYsR6Zpej2CSJtIuPHWM4eTKXuchAdGlS+ea\nxUlzcGoRNKq4EGQtxeDqTVayEnmOmhn9+AmeQEZQYncRi8U7IRM=\n=vvCA\n-----END PGP SIGNATURE-----",
        "source": "",
        "source_url": null
      }
    ]
  }
}
```

**Comment by yoeluk** [comment]
but 
```
$ curl https://registry.terraform.io/v1/providers/jfrog/artifactory/2.2.15/download/linux/amd64 | jq                                                                                                          135ms  Tue 14 Dec 17:21:14 2021
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    64  100    64    0     0    264      0 --:--:-- --:--:-- --:--:--   264
{
  "errors": [
    "signing key 6B219DCCD7639232 not found for jfrog"
  ]
}
```

**Comment by alexhung** [comment]
@yoeluk I just tried the curl and looks like 2.2.15 is now available. Can you check?

**Comment by yoeluk** [comment]
@alexhung It is available now here too! Thank you so much for the support!!

**Comment by alexhung** [comment]
Closing this issue as it looks like normal service has resumed.

Please create new issue if you encounter this signing problem.

**Comment by martinm82** [comment]
I tried with 2.6.20, 21 and 22 and none of them works. I still get 

```
 Provider registry.terraform.io/jfrog/artifactory v2.6.21 does not have a package available for your current platform, darwin_amd64.
```

Only working version is 2.6.23.

**Comment by szubster** [comment]
@alexhung We also experience same issue as Martin.

**Comment by roehrijn** [comment]
I can confirm that only some versions are working. 

**Working:** 
2.16.23
2.16.21
2.16.20
2.16.17

**Not working:**
2.16.22
2.16.19
2.16.18

**Comment by maxdanilov** [comment]
@alexhung 2.2.15 still does not work for us in Terraform Cloud as well:
```
Provider registry.terraform.io/jfrog/artifactory v2.2.15 does not have a
package available for your current platform, linux_amd64.
```

**Comment by RussellRollins** [comment]
@roehrijn I have the same behavior, certain versions work, and certain versions do not.

Based on some of the cache headers in the response:

```
$ curl -I -sSL registry.terraform.io/v1/providers/jfrog/artifactory/2.6.19/download/linux/amd64
HTTP/1.1 404 Not Found
Content-Type: application/json
Cache-Control: max-age=604800, stale-if-error=31536000, public
Last-Modified: Fri, 10 Dec 2021 17:11:14 GMT
Server: terraform-registry/1c82389f253fa390f5c803030473e97cd6b1134f
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Via: 1.1 varnish, 1.1 varnish
Content-Length: 64
Accept-Ranges: bytes
Date: Wed, 15 Dec 2021 14:17:31 GMT
Age: 85225
Connection: keep-alive
X-Served-By: cache-iad-kjyo7100070-IAD, cache-mdw17358-MDW
X-Cache: HIT, HIT
X-Cache-Hits: 1, 1
Vary: Accept-Encoding, X-Terraform-Version
```

I suspect that the Terraformer Registry is fronted by some kind of CDN, which may be caching the "bad" responses from the issue for a long time because they were 404s.

**Comment by alexhung** [comment]
TF has confirmed that caching/CDN seems to be the issue. They are looking into this.

**Comment by alexhung** [comment]
@martinm82 @szubster @roehrijn @maxdanilov @RussellRollins TF just informed me that they've purged the cache and all versions should be available.

Please report back here if you still have issue downloading your version. TF has another purge mechanism that is "more heavy-handed". 😄

**Comment by RussellRollins** [comment]
I'm still seeing some issues from my local CDN POP, but it looks like our CI build is going to pass, so hopefully it's propagating out now! Thanks for all the attention folks.
